Run migration

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -298,6 +298,56 @@ jobs:
       # - destroy-environment
 
 
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: cimg/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+      - attach_workspace:
+          at: .
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            echo ENVIRONMENT=production > ".env"
+            echo TYPEORM_CONNECTION=postgres >> ".env"
+            echo TYPEORM_ENTITIES=./src/modules/domain/*/*/*.entity.ts >> ".env"
+            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
+            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
+            echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
+            echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
+            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
+            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
+            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
+            echo "npm install"
+            npm install
+            echo $?
+            echo "npm migrations"
+            npm run migrations > migrations_dump.txt
+            echo $?
+            echo "-------------------------------"
+            cat migrations_dump.txt 
+            echo "------------------------------"
+      - run:
+          name: Send migration results to memstash
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+              echo 'Migrated successfully'
+              curl https://kvdb.io/VGVHHkNaBtgymEymuBrdpU/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            else:
+              echo 'Migration failed'
+              curl https://kvdb.io/VGVHHkNaBtgymEymuBrdpU/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '0'
+            fi
+    # Here's where you will add some code to rollback on failure    
+      # - slack/notify:
+      #     event: fail
+      #     template: basic_fail_1     
+
+
+
   # build-backend:
   #   docker:
   #     - image: circleci/node:13.8.0
@@ -535,8 +585,8 @@ workflows:
               only: [master]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
       # - deploy-frontend:
       #     requires: [run-migrations]
       # - deploy-backend:
